version: "3.7"

services:
  app:
    image: python:3.12-slim
    container_name: backup
    user: "1000:1000"
    working_dir: /app
    volumes:
      - ./app:/app
      - ./scripts:/scripts:ro
    command: python server.py
