version: "3.7"

services:
  server:
    image: tomasvalenta/umbrel-backup:latest
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/../:/umbrel-apps
    environment:
      - TZ=Europe/Prague
