version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: tomasvalenta-backup_server_1
      APP_PORT: 5000

  server:
    image: cz840311/umbrel-backup:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "${APP_PORT}:5000"
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/../:/umbrel-root
      - /media:/media
    environment:
      - TZ=Europe/Prague
